# .golangci.yml - Configuração de Lint Enterprise-Grade
# Restaurado para padrões de alta qualidade com suporte a CGO isolado via build tags

run:
  timeout: 10m
  modules-download-mode: readonly
  allow-parallel-runners: true
  # Importante: o lint deve rodar sem CGO para garantir portabilidade da análise
  go: '1.24'

linters:
  disable-all: true
  enable:
    - typecheck    # Fundamental: validação de tipos e imports
    - staticcheck  # Qualidade e bugs latentes
    - ineffassign  # Atribuições inúteis
    - govet        # Erros lógicos comuns
    - errcheck     # Tratamento de erros
    - gosimple     # Simplificação de código
    - bodyclose    # Fechamento de recursos (HTTP)
    - misspell     # Ortografia

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new: false

linters-settings:
  govet:
    enable:
      - shadow
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: true

severity:
  default-severity: error
