# .golangci.yml - Configuração de Lint Progressivo (Enterprise-Grade)
# Foco: Qualidade sem quebrar a entrega, impedindo regressões em código novo.

run:
  timeout: 10m
  modules-download-mode: readonly
  # Permite que o lint passe se o código legado tiver erros, 
  # mas bloqueia se código novo introduzir problemas.
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - govet        # Reporta erros comuns de lógica e suspeitos
    - errcheck     # Garante que erros retornados sejam tratados
    - gosimple     # Sugere simplificações de código
    - bodyclose    # Verifica se o corpo de requisições HTTP foi fechado (crítico para Go)
    - misspell     # Corrige erros de ortografia comuns no código

issues:
  # Máximo de problemas por linter - 0 significa ilimitado
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Regras de exclusão para reduzir ruído inicial
  exclude-use-default: false
  
  # Prioriza problemas em código novo
  new: false
  # Removido new-from-rev daqui para ser controlado via CLI no ci.yml

linters-settings:
  govet:
    enable:
      - shadow
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: true

severity:
  default-severity: error
